### ISSUE TITLE
Finalize layout of homepage and current department page.

### ISSUE THREAD

**Issue by ryankinzer** [NPTfisheries/nptfisheries#18]
Currently, there is overlap between the homepage and department page. Much of the content could be combined onto a single page. We need to determine the final organization of the website, and then wireframe each page to determine the final layout and necessary components.

**Comment by ryankinzer** [comment]
Homepage: add rotating projects for dynamic content.

Remove: Department Page from NavBar and add pages for Divisions and Projects.

**Comment by tylerstright** [comment]
On Divisions page (formerly Departments):

Remove department description and projects links.

Update the look of the Division blurbs

**Comment by ryankinzer** [comment]
Re-worked the home, department, division, and project pages. Not all of Tyler's suggestions were included. Closing the issue for now and we can revisit the other suggestions later after we have used the new formatted pages for a bit.
