### ISSUE TITLE
Improve the appearance of multi-select

### ISSUE THREAD

**Issue by tylerstright** [NPTfisheries/nptfisheries#20]
Upload Documents: Employee Authors

We should build CSS to style these elements to be reused throughout the app.  Selects, buttons, multi-select, etc.

**Comment by tylerstright** [comment]
In documents/forms.py on line 17, we can do:

            'employee_authors': forms.SelectMultiple(attrs={'class': 'form-select', 'size': 10, 'placeholder':'Secondary Authors'}),

which I think makes the multiselect acceptable. the 'size' attribute determines how many lines are visible in the select box.

**Comment by ryankinzer** [comment]
Completed.  Also added consistent bootstrap style to all forms.
